### PR TITLE
improve test for contract update, fix contract migration during code upgrade

### LINKED ISSUE #316: Verify (via cluster test, e.g.) that pending signatures during V1 -> V2 upgrade will correctly resume with a timeout error despite being cleared from the state due to migration

### PR DESCRIPTION
**Pull request by kevindeforth**
Resolves #316 and partially addresses #318.

This PR: 
- changes the migration logic. Contract updates are now stored under a new StorageKey, to avoid the behavior described in #318, in the sense that we no longer inherit existing proposals.
- introduces more state to the legacy contract before updating.
- cleans up some fields that are no longer required since #296 

A follow up is required (c.f. #329)

### CODE REVIEW

File: libs/chain-signatures/contract/src/update.rs [hunk 1]
```diff
@@ -57,6 +57,9 @@ pub struct ProposeUpdateArgs {
 #[near(serializers=[borsh ])]
 #[derive(Debug)]
 struct UpdateEntry {
+    // todo:
```
Comment (bowenwang1996) [inline libs/chain-signatures/contract/src/update.rs:60]: create an issue for this?

**Review by bowenwang1996 — APPROVED** [review]
